'''
Pentagon numbers

Pentagonal numbers are generated by the formula,
Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8.
However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk,
for which their sum and difference are pentagonal
and D = |Pk − Pj| is minimised; what is the value of D?
'''
from time import perf_counter as time

t = time()

def isPenta(n):
	s = (1/2+((24*n+1)/4)**.5)/3
	if s%1 == 0: return 1

def pentaFind():
	penta = set()
	pentalist = [1]
	n = 2

	while True:
		Pn = n*(3*n-1)//2
		penta.add(Pn)
		pentalist.append(Pn)
		for p1 in pentalist:
			p2 = Pn-p1
			if p2 in penta:
				if isPenta(Pn+p1):
					return(p2)
		n += 1

print(pentaFind())
print(time()-t)
