'''
Triangular, pentagonal, and hexagonal

Triangle, pentagonal, and hexagonal numbers
are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
'''
from time import perf_counter as time

t = time()
limit = 100000

# T = {n*(n+1)/2 for n in range(limit)}
# triangle numbers also are Hexagonal
P = {n*(3*n-1)/2 for n in range(limit)}
H = {n*(2*n-1) for n in range(limit)}

s = sorted(filter(lambda n:n>40755,P&H))
print(s) # 1533776805
print(time()-t)

#### 2
t = time()
n = 144

while True:
	H = n*(2*n-1)
	p = (1+(24*H+1)**.5)/6
	if p%1==0:
		print(H)
		break
	n+=1
print(time()-t)
